language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
#  - "nightly" # currently points to 3.7-dev

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install codecov"

# command to run tests
# Use --nocapture with nosetests to get extra verbose output for debugging on Travis
script:
  - nosetests -v --with-coverage --cover-package=diagnostic_primers

# application dependencies: BLAST+, legacy BLAST, Primer3, EMBOSS
before_install:
  - cd $HOME
  # Install BLAST
  - wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy/2.2.26/blast-2.2.26-x64-linux.tar.gz
  - tar -zxf blast-2.2.26-x64-linux.tar.gz
  - export PATH=$HOME/blast-2.2.26/bin:$PATH
  - mkdir primer3
  - cd primer3
  - wget https://sourceforge.net/projects/primer3/files/primer3/1.1.4/primer3-1.1.4.tar.gz
  - tar -zxf primer3-1.1.4.tar.gz
  - cd src
  - make all
  - cd $HOME
  - export PATH=$HOME/primer3/src  
  - cd $TRAVIS_BUILD_DIR

sudo: false
addons:
  apt:
    packages:
    - ncbi-blast+
    - emboss

# Use codecov for code coverage
after_success:
  - codecov